# Generated by Django 3.1 on 2020-08-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcards',
            name='expiry',
        ),
        migrations.AddField(
            model_name='paymentcards',
            name='expiry_month',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentcards',
            name='expiry_year',
            field=models.CharField(default='3030', max_length=4),
        ),
        migrations.AddField(
            model_name='paymentcards',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
